//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.12 at 04:33:57 GMT-06:00 
//


package edu.utexas.barad.test.input.impl;

public class JAXBVersion {

    public final static java.lang.String version = "1.0.4";

}
