/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_utexas_barad_agent_AgentUtils */

#ifndef _Included_edu_utexas_barad_agent_AgentUtils
#define _Included_edu_utexas_barad_agent_AgentUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_utexas_barad_agent_AgentUtils
 * Method:    getSWTClassLoaderImpl
 * Signature: ()Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL Java_edu_utexas_barad_agent_AgentUtils_getSWTClassLoaderImpl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
