/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_utexas_barad_agent_swt_widgets_MessageBoxHelper */

#ifndef _Included_edu_utexas_barad_agent_swt_widgets_MessageBoxHelper
#define _Included_edu_utexas_barad_agent_swt_widgets_MessageBoxHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_utexas_barad_agent_swt_widgets_MessageBoxHelper
 * Method:    clickButton
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_utexas_barad_agent_swt_widgets_MessageBoxHelper_clickButton
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_utexas_barad_agent_swt_widgets_MessageBoxHelper
 * Method:    newInstance
 * Signature: (I)Ledu/utexas/barad/agent/swt/widgets/MessageBoxHelper;
 */
JNIEXPORT jobject JNICALL Java_edu_utexas_barad_agent_swt_widgets_MessageBoxHelper_newInstance
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
