//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.12 at 04:33:57 GMT-06:00 
//


package edu.utexas.barad.test.input.impl;

public class WidgetinputImpl implements edu.utexas.barad.test.input.Widgetinput, com.sun.xml.bind.JAXBObject, edu.utexas.barad.test.input.impl.runtime.UnmarshallableObject, edu.utexas.barad.test.input.impl.runtime.XMLSerializable, edu.utexas.barad.test.input.impl.runtime.ValidatableObject
{

    protected java.lang.String _Value;
    protected boolean has_Index;
    protected short _Index;
    protected java.lang.String _Widgetid;
    protected java.lang.String _Parentclass;
    protected java.lang.String _Parentid;
    protected java.lang.String _Widgetclass;
    protected java.lang.String _Widgetproperty;
    public final static java.lang.Class version = (edu.utexas.barad.test.input.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (edu.utexas.barad.test.input.Widgetinput.class);
    }

    public java.lang.String getValue() {
        return _Value;
    }

    public void setValue(java.lang.String value) {
        _Value = value;
    }

    public short getIndex() {
        return _Index;
    }

    public void setIndex(short value) {
        _Index = value;
        has_Index = true;
    }

    public java.lang.String getWidgetid() {
        return _Widgetid;
    }

    public void setWidgetid(java.lang.String value) {
        _Widgetid = value;
    }

    public java.lang.String getParentclass() {
        return _Parentclass;
    }

    public void setParentclass(java.lang.String value) {
        _Parentclass = value;
    }

    public java.lang.String getParentid() {
        return _Parentid;
    }

    public void setParentid(java.lang.String value) {
        _Parentid = value;
    }

    public java.lang.String getWidgetclass() {
        return _Widgetclass;
    }

    public void setWidgetclass(java.lang.String value) {
        _Widgetclass = value;
    }

    public java.lang.String getWidgetproperty() {
        return _Widgetproperty;
    }

    public void setWidgetproperty(java.lang.String value) {
        _Widgetproperty = value;
    }

    public edu.utexas.barad.test.input.impl.runtime.UnmarshallingEventHandler createUnmarshaller(edu.utexas.barad.test.input.impl.runtime.UnmarshallingContext context) {
        return new edu.utexas.barad.test.input.impl.WidgetinputImpl.Unmarshaller(context);
    }

    public void serializeBody(edu.utexas.barad.test.input.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (!has_Index) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "Index"));
        }
        context.startElement("http://tempuri.org/XMLSchema.xsd", "parentid");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Parentid), "Parentid");
        } catch (java.lang.Exception e) {
            edu.utexas.barad.test.input.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://tempuri.org/XMLSchema.xsd", "parentclass");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Parentclass), "Parentclass");
        } catch (java.lang.Exception e) {
            edu.utexas.barad.test.input.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://tempuri.org/XMLSchema.xsd", "widgetid");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Widgetid), "Widgetid");
        } catch (java.lang.Exception e) {
            edu.utexas.barad.test.input.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://tempuri.org/XMLSchema.xsd", "widgetclass");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Widgetclass), "Widgetclass");
        } catch (java.lang.Exception e) {
            edu.utexas.barad.test.input.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://tempuri.org/XMLSchema.xsd", "index");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(javax.xml.bind.DatatypeConverter.printShort(((short) _Index)), "Index");
        } catch (java.lang.Exception e) {
            edu.utexas.barad.test.input.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://tempuri.org/XMLSchema.xsd", "widgetproperty");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Widgetproperty), "Widgetproperty");
        } catch (java.lang.Exception e) {
            edu.utexas.barad.test.input.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://tempuri.org/XMLSchema.xsd", "value");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Value), "Value");
        } catch (java.lang.Exception e) {
            edu.utexas.barad.test.input.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
    }

    public void serializeAttributes(edu.utexas.barad.test.input.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (!has_Index) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "Index"));
        }
    }

    public void serializeURIs(edu.utexas.barad.test.input.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (!has_Index) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "Index"));
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (edu.utexas.barad.test.input.Widgetinput.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnam"
+"eClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.gram"
+"mar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcon"
+"tentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataE"
+"xp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006excep"
+"tq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000#com"
+".sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidx"
+"r\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%"
+"com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun."
+"msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012"
+"Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000\u0018L\u0000\nwhiteSpacet\u0000.Lcom/sun/m"
+"sv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2"
+"001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpac"
+"eProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.W"
+"hiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expr"
+"ession$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.u"
+"til.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0018L\u0000\fnamespaceURIq\u0000~"
+"\u0000\u0018xpq\u0000~\u0000\u001cq\u0000~\u0000\u001bsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq"
+"\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq"
+"\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\fxq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z"
+"\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0010ppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0015q\u0000~\u0000\u001bt\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.Whit"
+"eSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001eq\u0000~\u0000!sq\u0000~\u0000\"q\u0000~\u0000-q\u0000~"
+"\u0000\u001bsr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocal"
+"Nameq\u0000~\u0000\u0018L\u0000\fnamespaceURIq\u0000~\u0000\u0018xr\u0000\u001dcom.sun.msv.grammar.NameCla"
+"ss\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-in"
+"stancesr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000(\u0001psq\u0000~\u00001t\u0000\bparentidt\u0000 http://tempuri.or"
+"g/XMLSchema.xsdsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0013sq\u0000~\u0000$ppsq\u0000~\u0000&q\u0000~\u0000)pq\u0000~"
+"\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t\u0000\u000bparentclassq\u0000~\u0000;sq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0013s"
+"q\u0000~\u0000$ppsq\u0000~\u0000&q\u0000~\u0000)pq\u0000~\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t\u0000\bwidgetidq\u0000~\u0000;sq\u0000~"
+"\u0000\u000bpp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0013sq\u0000~\u0000$ppsq\u0000~\u0000&q\u0000~\u0000)pq\u0000~\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t"
+"\u0000\u000bwidgetclassq\u0000~\u0000;sq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0010ppsr\u0000\"com.sun.msv.d"
+"atatype.xsd.ShortType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.datatype.xsd"
+".IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetst\u0000)Lcom/sun/msv/d"
+"atatype/xsd/XSDatatypeImpl;xq\u0000~\u0000\u0015q\u0000~\u0000\u001bt\u0000\u0005shortq\u0000~\u0000/sr\u0000*com.s"
+"un.msv.datatype.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun."
+"msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet\u0000\u0012Ljava/"
+"lang/Object;xr\u00009com.sun.msv.datatype.xsd.DataTypeWithValueCo"
+"nstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.DataTyp"
+"eWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFlagL\u0000\b"
+"baseTypeq\u0000~\u0000SL\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/xsd/Con"
+"creteType;L\u0000\tfacetNameq\u0000~\u0000\u0018xq\u0000~\u0000\u0017ppq\u0000~\u0000/\u0000\u0001sr\u0000*com.sun.msv.da"
+"tatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Wppq\u0000~\u0000/\u0000\u0000sr\u0000 co"
+"m.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Rq\u0000~\u0000\u001bt\u0000\u0003intq\u0000"
+"~\u0000/sq\u0000~\u0000Vppq\u0000~\u0000/\u0000\u0001sq\u0000~\u0000]ppq\u0000~\u0000/\u0000\u0000sr\u0000!com.sun.msv.datatype.xs"
+"d.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Rq\u0000~\u0000\u001bt\u0000\u0004longq\u0000~\u0000/sq\u0000~\u0000Vppq\u0000~\u0000/\u0000\u0001s"
+"q\u0000~\u0000]ppq\u0000~\u0000/\u0000\u0000sr\u0000$com.sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Rq\u0000~\u0000\u001bt\u0000\u0007integerq\u0000~\u0000/sr\u0000,com.sun.msv.datatype.xsd."
+"FractionDigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.dataty"
+"pe.xsd.DataTypeWithLexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000Zpp"
+"q\u0000~\u0000/\u0001\u0000sr\u0000#com.sun.msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\u0015q\u0000~\u0000\u001bt\u0000\u0007decimalq\u0000~\u0000/q\u0000~\u0000pt\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000jt\u0000\fmin"
+"Inclusivesr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang."
+"Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000jt\u0000\fmaxInclusivesq\u0000~\u0000t\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff"
+"\u00ffq\u0000~\u0000eq\u0000~\u0000ssr\u0000\u0011java.lang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000u\u0080\u0000\u0000"
+"\u0000q\u0000~\u0000eq\u0000~\u0000wsq\u0000~\u0000y\u007f\u00ff\u00ff\u00ffq\u0000~\u0000`q\u0000~\u0000ssr\u0000\u000fjava.lang.ShorthM7\u00134`\u00daR\u0002\u0000"
+"\u0001S\u0000\u0005valuexq\u0000~\u0000u\u0080\u0000q\u0000~\u0000`q\u0000~\u0000wsq\u0000~\u0000|\u007f\u00ffq\u0000~\u0000!sq\u0000~\u0000\"q\u0000~\u0000Uq\u0000~\u0000\u001bsq\u0000~"
+"\u0000$ppsq\u0000~\u0000&q\u0000~\u0000)pq\u0000~\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t\u0000\u0005indexq\u0000~\u0000;sq\u0000~\u0000\u000bpp\u0000s"
+"q\u0000~\u0000\u0000ppq\u0000~\u0000\u0013sq\u0000~\u0000$ppsq\u0000~\u0000&q\u0000~\u0000)pq\u0000~\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t\u0000\u000ewidg"
+"etpropertyq\u0000~\u0000;sq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0013sq\u0000~\u0000$ppsq\u0000~\u0000&q\u0000~\u0000)pq\u0000~"
+"\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t\u0000\u0005valueq\u0000~\u0000;sr\u0000\"com.sun.msv.grammar.Expre"
+"ssionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/Expre"
+"ssionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPoo"
+"l$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$L"
+"com/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u0014\u0001pq\u0000~\u0000%q\u0000~\u0000>q\u0000~\u0000Dq\u0000"
+"~\u0000Jq\u0000~\u0000\u0080q\u0000~\u0000\u0007q\u0000~\u0000\u0086q\u0000~\u0000\u008cq\u0000~\u0000Oq\u0000~\u0000\u000fq\u0000~\u0000=q\u0000~\u0000Cq\u0000~\u0000\tq\u0000~\u0000Iq\u0000~\u0000\u0085q\u0000"
+"~\u0000\u008bq\u0000~\u0000\u0005q\u0000~\u0000\nq\u0000~\u0000\bq\u0000~\u0000\u0006x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends edu.utexas.barad.test.input.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(edu.utexas.barad.test.input.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------------");
        }

        protected Unmarshaller(edu.utexas.barad.test.input.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return edu.utexas.barad.test.input.impl.WidgetinputImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        if (("index" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        break;
                    case  3 :
                        if (("parentclass" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        break;
                    case  18 :
                        if (("value" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 19;
                            return ;
                        }
                        break;
                    case  21 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  9 :
                        if (("widgetclass" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        break;
                    case  15 :
                        if (("widgetproperty" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 16;
                            return ;
                        }
                        break;
                    case  6 :
                        if (("widgetid" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        break;
                    case  0 :
                        if (("parentid" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  14 :
                        if (("index" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("parentclass" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  21 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("parentid" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("widgetid" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("widgetclass" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  17 :
                        if (("widgetproperty" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  20 :
                        if (("value" == ___local)&&("http://tempuri.org/XMLSchema.xsd" == ___uri)) {
                            context.popAttributes();
                            state = 21;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  21 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  21 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  13 :
                            eatText1(value);
                            state = 14;
                            return ;
                        case  21 :
                            revertToParentFromText(value);
                            return ;
                        case  16 :
                            eatText2(value);
                            state = 17;
                            return ;
                        case  10 :
                            eatText3(value);
                            state = 11;
                            return ;
                        case  7 :
                            eatText4(value);
                            state = 8;
                            return ;
                        case  4 :
                            eatText5(value);
                            state = 5;
                            return ;
                        case  1 :
                            eatText6(value);
                            state = 2;
                            return ;
                        case  19 :
                            eatText7(value);
                            state = 20;
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Index = javax.xml.bind.DatatypeConverter.parseShort(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_Index = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Widgetproperty = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Widgetclass = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Widgetid = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Parentclass = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText6(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Parentid = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText7(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Value = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
