//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.12 at 04:33:57 GMT-06:00 
//


package edu.utexas.barad.test.input;


/**
 * Java content class for widgetinput complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/workspace_symbolicexecution/GUITestInput/schema/GUITestInput.xsd line 3)
 * <p>
 * <pre>
 * &lt;complexType name="widgetinput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parentid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parentclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="widgetid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="widgetclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="widgetproperty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Widgetinput {


    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getValue();

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setValue(java.lang.String value);

    /**
     * Gets the value of the index property.
     * 
     */
    short getIndex();

    /**
     * Sets the value of the index property.
     * 
     */
    void setIndex(short value);

    /**
     * Gets the value of the widgetid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getWidgetid();

    /**
     * Sets the value of the widgetid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setWidgetid(java.lang.String value);

    /**
     * Gets the value of the parentclass property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getParentclass();

    /**
     * Sets the value of the parentclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setParentclass(java.lang.String value);

    /**
     * Gets the value of the parentid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getParentid();

    /**
     * Sets the value of the parentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setParentid(java.lang.String value);

    /**
     * Gets the value of the widgetclass property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getWidgetclass();

    /**
     * Sets the value of the widgetclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setWidgetclass(java.lang.String value);

    /**
     * Gets the value of the widgetproperty property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getWidgetproperty();

    /**
     * Sets the value of the widgetproperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setWidgetproperty(java.lang.String value);

}
