//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.12 at 04:33:57 GMT-06:00 
//


package edu.utexas.barad.test.input;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.utexas.barad.test.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends edu.utexas.barad.test.input.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static edu.utexas.barad.test.input.impl.runtime.GrammarInfo grammarInfo = new edu.utexas.barad.test.input.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (edu.utexas.barad.test.input.ObjectFactory.class));
    public final static java.lang.Class version = (edu.utexas.barad.test.input.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((edu.utexas.barad.test.input.Suite.class), "edu.utexas.barad.test.input.impl.SuiteImpl");
        defaultImplementations.put((edu.utexas.barad.test.input.Widgetinput.class), "edu.utexas.barad.test.input.impl.WidgetinputImpl");
        defaultImplementations.put((edu.utexas.barad.test.input.Testsuite.class), "edu.utexas.barad.test.input.impl.TestsuiteImpl");
        defaultImplementations.put((edu.utexas.barad.test.input.Testcase.class), "edu.utexas.barad.test.input.impl.TestcaseImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://tempuri.org/XMLSchema.xsd", "testsuite"), (edu.utexas.barad.test.input.Testsuite.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.utexas.barad.test.input
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @param value
     *     the value of the property to be set
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Suite
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public edu.utexas.barad.test.input.Suite createSuite()
        throws javax.xml.bind.JAXBException
    {
        return new edu.utexas.barad.test.input.impl.SuiteImpl();
    }

    /**
     * Create an instance of Widgetinput
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public edu.utexas.barad.test.input.Widgetinput createWidgetinput()
        throws javax.xml.bind.JAXBException
    {
        return new edu.utexas.barad.test.input.impl.WidgetinputImpl();
    }

    /**
     * Create an instance of Testsuite
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public edu.utexas.barad.test.input.Testsuite createTestsuite()
        throws javax.xml.bind.JAXBException
    {
        return new edu.utexas.barad.test.input.impl.TestsuiteImpl();
    }

    /**
     * Create an instance of Testcase
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public edu.utexas.barad.test.input.Testcase createTestcase()
        throws javax.xml.bind.JAXBException
    {
        return new edu.utexas.barad.test.input.impl.TestcaseImpl();
    }

}
