//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.12 at 02:49:56 PM GMT-06:00 
//


package edu.utexas.barad.test.input;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.utexas.barad.test.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Testsuite_QNAME = new QName("http://tempuri.org/XMLSchema.xsd", "testsuite");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.utexas.barad.test.input
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WidgetInput }
     * 
     */
    public WidgetInput createWidgetInput() {
        return new WidgetInput();
    }

    /**
     * Create an instance of {@link TestSuite }
     * 
     */
    public TestSuite createTestSuite() {
        return new TestSuite();
    }

    /**
     * Create an instance of {@link TestCase }
     * 
     */
    public TestCase createTestCase() {
        return new TestCase();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestSuite }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/XMLSchema.xsd", name = "testsuite")
    public JAXBElement<TestSuite> createTestsuite(TestSuite value) {
        return new JAXBElement<TestSuite>(_Testsuite_QNAME, TestSuite.class, null, value);
    }

}
