//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.12 at 04:33:57 GMT-06:00 
//


package edu.utexas.barad.test.input;


/**
 * Java content class for testsuite element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/workspace_symbolicexecution/GUITestInput/schema/GUITestInput.xsd line 19)
 * <p>
 * <pre>
 * &lt;element name="testsuite" type="{http://tempuri.org/XMLSchema.xsd}suite"/>
 * </pre>
 * 
 */
public interface Testsuite
    extends javax.xml.bind.Element, edu.utexas.barad.test.input.Suite
{


}
