//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.23 at 05:13:07 GMT-06:00 
//


package org.barad.test.input;


/**
 * Java content class for inputs element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/workspace_symbolicexecution/GUITestInput/schema/GUITestInput.xsd line 8)
 * <p>
 * <pre>
 * &lt;element name="inputs" type="{http://tempuri.org/XMLSchema.xsd}input"/>
 * </pre>
 * 
 */
public interface Inputs
    extends javax.xml.bind.Element, org.barad.test.input.Input
{


}
