//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.23 at 05:13:07 GMT-06:00 
//


package org.barad.test.input;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.barad.test.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends org.barad.test.input.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static org.barad.test.input.impl.runtime.GrammarInfo grammarInfo = new org.barad.test.input.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (org.barad.test.input.ObjectFactory.class));
    public final static java.lang.Class version = (org.barad.test.input.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((org.barad.test.input.Inputs.class), "org.barad.test.input.impl.InputsImpl");
        defaultImplementations.put((org.barad.test.input.Values.class), "org.barad.test.input.impl.ValuesImpl");
        defaultImplementations.put((org.barad.test.input.Input.class), "org.barad.test.input.impl.InputImpl");
        defaultImplementations.put((org.barad.test.input.Widget.class), "org.barad.test.input.impl.WidgetImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://tempuri.org/XMLSchema.xsd", "inputs"), (org.barad.test.input.Inputs.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.barad.test.input
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @param value
     *     the value of the property to be set
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Inputs
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.barad.test.input.Inputs createInputs()
        throws javax.xml.bind.JAXBException
    {
        return new org.barad.test.input.impl.InputsImpl();
    }

    /**
     * Create an instance of Values
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.barad.test.input.Values createValues()
        throws javax.xml.bind.JAXBException
    {
        return new org.barad.test.input.impl.ValuesImpl();
    }

    /**
     * Create an instance of Input
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.barad.test.input.Input createInput()
        throws javax.xml.bind.JAXBException
    {
        return new org.barad.test.input.impl.InputImpl();
    }

    /**
     * Create an instance of Widget
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.barad.test.input.Widget createWidget()
        throws javax.xml.bind.JAXBException
    {
        return new org.barad.test.input.impl.WidgetImpl();
    }

}
