//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.23 at 05:13:07 GMT-06:00 
//


package org.barad.test.input;


/**
 * Java content class for widget complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/workspace_symbolicexecution/GUITestInput/schema/GUITestInput.xsd line 10)
 * <p>
 * <pre>
 * &lt;complexType name="widget">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clazz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="values" type="{http://tempuri.org/XMLSchema.xsd}values"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Widget {


    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link org.barad.test.input.Values}
     */
    org.barad.test.input.Values getValues();

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.barad.test.input.Values}
     */
    void setValues(org.barad.test.input.Values value);

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getParent();

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setParent(java.lang.String value);

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIndex();

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIndex(java.lang.String value);

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getClazz();

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setClazz(java.lang.String value);

}
